# Generated by Django 2.2.7 on 2019-11-12 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(null=True)),
                ('vat_registered', models.BooleanField(default=False)),
                ('subtotal', models.FloatField(null=True)),
                ('vat', models.FloatField(null=True)),
                ('total', models.FloatField()),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('terms', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
