# Generated by Django 2.2.7 on 2019-11-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='creator',
        ),
    ]
