# Generated by Django 2.2.7 on 2019-11-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20191113_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='vat',
            field=models.FloatField(default=0, null=True),
        ),
    ]
