# Generated by Django 2.2.7 on 2019-11-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_remove_invoice_creator'),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invoices',
            field=models.ManyToManyField(blank=True, related_name='creator', to='invoices.Invoice'),
        ),
    ]
